<?php

namespace AppBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * CategoryRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CategoryRepository extends EntityRepository
{

	public function findAllOrderedOne() {
		$dq = 'SELECT x FROM AppBundle\Entity\Category x ORDER BY x.name DESC';
		$query = $this->getEntityManager()->createQuery($dq);
		return $query->execute();
	}

	private function addFortuneCookieJoinSelect($qb){
		return $qb->leftJoin('cat.fortuneCookies', 'fc')->addSelect('fc');
	}

	public function findAllOrdered(){
		$qb = $this->createQueryBuilder('cat')
			->addOrderBy('cat.name','DESC');

		$this->addFortuneCookieJoinSelect($qb);

		$query = $qb->getQuery();
			
		return $query->execute();
	}

	public function search($val){
		$qb = $this->createQueryBuilder('cat')
			->andWhere('cat.name LIKE :searchVal
				OR cat.iconKey LIKE :searchVal
				OR fc.fortune LIKE :searchVal
				')
			->setParameter('searchVal', '%'.$val.'%');

		$this->addFortuneCookieJoinSelect($qb);
			
		return $qb	
			->getQuery()
			->execute();
	}

	public function findWithFortunesJoins($id){
		$qb = $this->createQueryBuilder('cat')
			->andWhere('cat.id = :id')
			->setParameter('id', $id);

		$this->addFortuneCookieJoinSelect($qb);

		return $qb
			->getQuery()
			->getOneOrNullResult();

	}

}
