<?php

namespace AppBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * CategoryRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CategoryRepository extends EntityRepository
{

	public function findAllOrdered() {
		/*SELECT * FROM category ORDER BY name DESC;*/
		$dq = 'SELECT x FROM AppBundle\Entity\Category x ORDER BY x.name DESC';
		$query = $this->getEntityManager()->createQuery($dq);

		/* montre sql*/
		/*var_dump($query->getSQL());die;*/

		return $query->execute();
	}
}
